In [11]:
import pandas as pd
import numpy as np

Importing Dataset

In [12]:
df = pd.read_csv("../data/raw/rapido_rides.csv")

In [13]:
df.head()

,services,date,time,ride_status,source,destination,duration,ride_id,distance,ride_charge,misc_charge,total_fare,payment_method
0,cab economy,2024-07-15,08:30:40.542646,completed,Balagere Harbor,Harohalli Nagar,38.0,RD3161218751875354,9.22,307.71,9.44,317.15,Amazon Pay
1,auto,2024-07-05,23:36:51.542646,completed,Basavanagudi 3rd Block,Bikasipura 1st Stage,14.0,RD8171514284594096,4.29,131.22,1.96,133.18,Paytm
2,auto,2024-07-23,11:05:37.542646,completed,Kormangala,Kothaguda Terrace,22.0,RD9376481122237926,7.35,NaN,NaN,NaN,NaN
3,cab economy,2024-06-24,08:45:10.542646,completed,koramangala,Kanakapura Arc,84.0,RD3676889143182765,17.48,558.48,1.57,560.05,QR scan
4,cab economy,2024-07-15,00:26:44.542646,completed,Ganganagar Cove,Basaveshwaranagar Colony,38.0,RD6639410275948084,17.63,543.02,9.17,552.19,Amazon Pay

In [14]:
df.shape

(51000, 13)

In [15]:
df.columns

Index(['services', 'date', 'time', 'ride_status', 'source', 'destination',
       'duration', 'ride_id', 'distance', 'ride_charge', 'misc_charge',
       'total_fare', 'payment_method'],
      dtype='object')

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51000 entries, 0 to 50999
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   services        51000 non-null  object
 1   date            51000 non-null  object
 2   time            51000 non-null  object
 3   ride_status     51000 non-null  object
 4   source          51000 non-null  object
 5   destination     51000 non-null  object
 6   duration        51000 non-null  float64
 7   ride_id         51000 non-null  object
 8   distance        51000 non-null  float64
 9   ride_charge     40654 non-null  float64
 10  misc_charge     40654 non-null  float64
 11  total_fare      40654 non-null  float64
 12  payment_method  38602 non-null  object
dtypes: float64(5), object(8)
memory usage: 5.1+ MB

In [17]:
df.describe()

           duration      distance   ride_charge   misc_charge    total_fare
count  51000.000000  51000.000000  40654.000000  40654.000000  40654.000000
mean      24.536157      7.080707    150.795340      7.966225    158.761565
std       19.086564      5.530099    144.497965      7.888836    144.716308
min        5.000000      0.800000     15.550000      0.000000     17.040000
25%       12.000000      3.310000     57.140000      2.290000     65.462500
50%       19.000000      5.500000     99.850000      5.520000    108.510000
75%       31.000000      9.070000    192.960000     11.070000    201.010000
max      180.000000     45.000000   1963.360000     50.000000   1990.940000